### ISSUE TITLE
compiler error

### ISSUE THREAD

**Issue by hy05190134** [openresty/stream-lua-nginx-module#100]
we find we should use bloody-dns-server branch to support the interface "ngx.req.udp_socket", but I find the ngx_stream_close_connection in ngx_stream_util.c is static in file ngx_stream_handler.c， so it use not compiler correctly.

**Comment by dndx** [comment]
Hello,

The bloody-dns-server branch has been deprecated and it does not support NGINX core newer than 1.11.2. We have a PR being reviewed that will support downstream UDP cosocket and once that is merged, will supersede the bloody-dns-server branch completely and work with latest NGINX cores.

**Comment by hy05190134** [comment]
@dndx  thanks, when to merge?

**Comment by dndx** [comment]
Hello,

No timeline yet as it is still being reviewed. If you wish you can clone https://github.com/openresty/stream-lua-nginx-module/tree/datong/udp_downstream manually and start using it today.

**Comment by dndx** [comment]
Closing this as UDP support has been released in OpenResty 1.13.6.2 RC1.

https://groups.google.com/forum/#!topic/openresty-en/bTfqTjshcX4
