### ISSUE TITLE
using stream-lua-nginx-module not prints log

### ISSUE THREAD

**Issue by xiongmaodada** [openresty/stream-lua-nginx-module#109]
when I use stream-lua-nginx-module proxy port to zookeeper port 2181，The code is as follows：
```
worker_processes  1;
error_log  logs/error.log;
events {
    worker_connections  1024;
}
stream {
        upstream backend {
            server 127.0.0.1:2181;
        }
        server {
            listen *:14330;
            content_by_lua_block {
                ngx.log(ngx.ERR, "=========ngx: ".. 1233333333333)
                ngx.say("Hello, Lua!")
            }
            proxy_pass backend;
        }
}
```

port 2181  is zookeeper's port,  when I  run command   **nc 127.0.0.1 14330** ，There is no such a result： **Hello, Lua!**
，also， error.log has not log:  
```
=========ngx: 1233333333333.
```
however，I modified the **server** code as follows：
```
server {
            listen *:14330;
            content_by_lua_block {
                ngx.log(ngx.ERR, "=========ngx: ".. 1233333333333)
                ngx.say("Hello, Lua!")
            }
            #proxy_pass backend;
 }
```

when I  also run   **nc 127.0.0.1 14330**  ， There is such a result： **Hello, Lua!**
 error.log has  log：
```
2018/05/05 21:12:25 [error] 17512#16888: *27 stream [lua] content_by_lua(nginx.conf:15):2: =========ngx: 1233333333333, client: 127.0.0.1, server: 0.0.0.0:14330
```

Why is there no print log in the first case？

**Comment by xiongmaodada** [comment]
Thank you for your answer, it's really helpful for me.

**Comment by xiongmaodada** [comment]
@dndx 
Hello,

I still have some questions as follows, look forward to your replay:
1. `preread_by_lua_block` phase is `preread`,  [order of lua nginx model directives](https://cloud.githubusercontent.com/assets/2137369/15272097/77d1c09e-1a37-11e6-97ef-d9767035fc3e.png): Initalization phase--->Rewrite/Access phase ---> Content phase ---> Log phase,
so does the  `preread` phase run between `Rewrite/Access` phase and `Content` phase ?

2.Can there be only one handler at each phase ? For example, there is only one between `proxy_pass` and `content_by_lua_block` at content phase.

**Comment by dndx** [comment]
@xiongmaodada 

1. The phase order for the stream subsystem is slightly different from http subsystem. You can check out a presentation I made at OpenResty Con 2017 for some detailed explanation: https://con.openresty.org/cn/2017/books/Intruduction%20to%20the%20NGINX%20stream%20subsystem%20and%20OpenResty's%20support.pdf
2. Content phase is unique as it can have only one handler. Other phases, such as preread, can have multiple handlers.
3. That really depends on the implementation of the directive and it is hard to provide an exhaustive list of this. But as far as the standard modules inside stream subsystem, I believe the proxy module and return module are the only two that uses content handlers.

**Comment by xiongmaodada** [comment]
Thank you ！！！
