### ISSUE TITLE
any example show how to use the directives of “preread_by_lua*”?

### ISSUE THREAD

**Issue by narci2010** [openresty/stream-lua-nginx-module#110]
as title.
thanks.

**Comment by narci2010** [comment]
in fact,i want to read ip from a file,and pass this ip to ""
preread_by_lua_block {
          file = io.open("/usr/share/nginx/html/ip" ,"r");  
             for line in file:lines() do   
                ipstr=line 
                if(string.len(ipstr)>6) then break end
             end  
          file:close()
          ipstr =ipstr..":3306" 
    }
proxy_pass $hserver;
but how can i pass ipstr value to $hserver?

**Comment by dndx** [comment]
Hello,

You can define a variable using [lua_add_variable](https://github.com/openresty/stream-lua-nginx-module#lua_add_variable) and set it in Lua using `ngx.var`. You can then pass it to `proxy_pass`.

**Comment by narci2010** [comment]
it works.
thx very muck!
