### ISSUE TITLE
Dynamic TCP proxy?

### ISSUE THREAD

**Issue by xgfd** [openresty/stream-lua-nginx-module#12]
Since the stream subsystem doesn't support variables, is it still possible to have dynamic TCP proxy that's similar to the example [DynamicRoutingBasedOnRedis](https://openresty.org/) shown on the official site?

**Comment by agentzh** [comment]
@xgfd Not really. Right now you are expected to do the proxying on the Lua land via something like this:

https://github.com/hamishforbes/lua-resty-upstream

**Comment by xgfd** [comment]
OK. Thanks for the information.
