### ISSUE TITLE
could be a bug

### ISSUE THREAD

**Issue by alpha2z** [openresty/stream-lua-nginx-module#13]
使用 openresty结合 stream_module 0.0.1版本，使用 mysql.lua和 redis.lua时，在协程切换的时候，出现 attempt to yield across metamethod/C-call boundary while handling client connection错误。use lua-5.1

**Comment by agentzh** [comment]
@alpha2z Please, not Chinese here. This place is considered English only. If you really want to use Chinese, please join the openresty (Chinese) mailing list instead. Please see https://openresty.org/en/community.html

Regarding your question, it seems that you are using these cosocket-based libraries in a wrong context (like in the top-level scope of a custom Lua module). The documentation of ngx_http_lua_module has explained this error in detail. Please see

https://github.com/openresty/lua-nginx-module#lua-coroutine-yieldingresuming

I also suggest you look at the openresty-survey and openresty.org demo applications based on OpenResty on how to use such resty.* libraries in the right way:

https://github.com/openresty/lua-nginx-module#lua-coroutine-yieldingresuming

https://github.com/openresty/openresty.org

**Comment by alpha2z** [comment]
thx.
