### ISSUE TITLE
Test failure in 140-ssl-c-api.t

### ISSUE THREAD

**Issue by dndx** [openresty/stream-lua-nginx-module#135]
When running `140-ssl-c-api.t` using the latest stream_lua, the following error are emitted:

```
Failed test 'TEST 1: simple cert + private key - pattern "[error]" should not match any line in error.log but matches line "2018/11/01 21:48:53 [error] 29321#0: *18 stream [lua] ssl_certificate_by_lua:11: no request found, context: ssl_certificate_by_lua*, client: unix:, server: unix:/home/datong/orinc/stream-lua-nginx-module/t/servroot/html/nginx.sock" (req 2)'
```

The problem is at https://github.com/openresty/stream-lua-nginx-module/blob/master/t/140-ssl-c-api.t#L92-L96. We need to update the tests to use the new resty.core method to get the request object after the ARM64 patch.

**Comment by thibaultcha** [comment]
I was about to send the same patch as part of this PR: https://github.com/openresty/stream-lua-nginx-module/pull/138 so I approved and merged it, thanks @spacewander
