### ISSUE TITLE
ngx.decode_args not achieve

### ISSUE THREAD

**Issue by chubbyhua** [openresty/stream-lua-nginx-module#14]
ngx.decode_args  didn't  achieved in stream-lua module

**Comment by agentzh** [comment]
@chubbyhua What do you mean? What code and configuration did you try and what exactly did you see?

**Comment by chubbyhua** [comment]
@agentzh 
my test configuration like this:
`stream {
    server {
        listen 5752;
        content_by_lua_block{
            local tbl = ngx.decode_args("a=1&b=hello&c=5") 
            ngx.say("hello,lua!")
        }
    }
}`

error msg like this :
`2016/04/21 10:25:05 [info] 15755#0: *1 client 127.0.0.1:46802 connected to 0.0.0.0:5752
2016/04/21 10:25:05 [error] 15755#0: *1 stream lua entry thread aborted: runtime error: content_by_lua(nginx.conf:36):2: attempt to call field 'decode_args' (a nil value)
stack traceback:
coroutine 0:
        content_by_lua(nginx.conf:36): in function <content_by_lua(nginx.conf:36):1> while handling client connection, client: 127.0.0.1, server: 0.0.0.0:5752`

**Comment by agentzh** [comment]
@chubbyhua Okay, the `ngx.encode_args` and `ngx.decode_args` are indeed missing in this module. I've just committed a patch to git master. Please try it out again on your side. Thanks!
