### ISSUE TITLE
Cannot get preread_by_lua_block work when ssl_preread on

### ISSUE THREAD

**Issue by saminiemi** [openresty/stream-lua-nginx-module#153]
I wonder why following code does not work. Lua block is not running at all. When I set ssl_preread off, it will run nicely.

```
worker_processes  1;

error_log /var/log/nginx/error.log info;

events {
    worker_connections  1024;
}

stream {
     server {
        listen 443;
        ssl_preread on;
        preread_by_lua_block {
            ngx.log(ngx.INFO, "I am not get running when ssl_preread on")
        }
        proxy_pass nexthop:443;
    }
}
```

Nginx v1.14.2, Lua module v0.10.13, Lua stream module v0.0.5 , running on Docker container based on original Nginx Dockerfile.

Thanks for any help!

**Comment by agentzh** [comment]
@dndx Will you have a look at this?

**Comment by saminiemi** [comment]
Thanks @agentzh !

@dndx if there is anything else you need, please let me know! I have also tried with most recent versions of moules, with same result.

**Comment by dndx** [comment]
@saminiemi Did you compiled openresty yourself? You need the patches in https://github.com/openresty/openresty/tree/master/patches applied for this to work properly. Or just use the release candidate based on 1.15.8 instead:

https://openresty.org/download/openresty-1.15.8.1rc0.tar.gz

**Comment by saminiemi** [comment]
@dndx Thanks a million, that was it! 

Patching Nginx source with nginx-1.15.8-stream_ssl_preread_no_skip.patch (obvious when see it:) made it work. 👍
