### ISSUE TITLE
cppcheck issues

### ISSUE THREAD

**Issue by chipitsine** [openresty/stream-lua-nginx-module#16]
[src/ngx_stream_lua_regex.c:444] -> [src/ngx_stream_lua_regex.c:465]: (warning) Possible null pointer dereference: lmcf - otherwise it is redundant to check it against null.

[src/ngx_stream_lua_regex.c:903] -> [src/ngx_stream_lua_regex.c:924]: (warning) Possible null pointer dereference: lmcf - otherwise it is redundant to check it against null.

[src/ngx_stream_lua_regex.c:1644] -> [src/ngx_stream_lua_regex.c:1665]: (warning) Possible null pointer dereference: lmcf - otherwise it is redundant to check it against null.

**Comment by agentzh** [comment]
@chipitsine Fixed. Thanks.
