### ISSUE TITLE
Browser maintains upstream across multiple hostnames.

### ISSUE THREAD

**Issue by ptmkarvinen** [openresty/stream-lua-nginx-module#161]
Hello!

We're trying to use this module to stream a secured connection, without terminating SSL, into a dynamically allocated upstream based on the hostname. Everything's working fine for the most part, but once a client is routed into a specific upstream, the browser (Chrome and Safari tested) is using that connection for all the hostnames. To put it short, preread_by_lua_block is only executed once, and won't be executed again until the client terminates the connection.

Here's a slightly simplified code example:
```
stream {
    lua_add_variable $target;
    
    server {
        listen 443;
        ssl_preread on;
        preread_by_lua_block {
            local servername = ngx.var.ssl_preread_server_name
            ngx.log(ngx.ERR,"Server Name: ",servername)
            
            if servername == "first.servername" then
                ngx.var.target = "first_upstream:443"
                return
            end

            if servername == "second.servername" then
                ngx.var.target = "second_upstream:443"
                return
            end 

        }
        proxy_pass $target;
    }
}
```

In the above, once the client visits first.servername, second.servername isn't routed into the correct upstream until client has terminated the browser session. cURL, or an equivalent tool, produces the correct routing every time as no session persists.

Is there some solution to this, that doesn't involve terminating SSL on this router?

**Comment by dndx** [comment]
No. Unless TLS is terminated there is no way to switch upstream in the middle of an established TLS connection. Otherwise TLS would failed its job of preventing impersonation from happening.

**Comment by ptmkarvinen** [comment]
Ahh, of course, that makes sense. Thanks a lot for the clarification, @dndx!
