### ISSUE TITLE
Test case failures on rhel7.6 ppc64le platform

### ISSUE THREAD

**Issue by SantoshMagdum** [openresty/stream-lua-nginx-module#178]
Hi All,

I had build the nginx binary on rhel 7.6 ppc64le (version 1.17.1.1rc0) from source code -  https://github.com/openresty/openresty.
Please note that, I had copied and used ppc64le compiled LuaJIT code while building openresty (nginx).
Below command I used to compile the openresty -
	
	
./configure --with-cc-opt="-DNGX_LUA_USE_ASSERT -DNGX_LUA_ABORT_AT_PANIC" --with-http_image_filter_module --with-http_dav_module  --with-http_auth_request_module --with-poll_module --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_ssl_module --with-http_iconv_module  --with-http_drizzle_module --with-http_postgres_module --with-http_addition_module --add-module=/usr/openresty/openresty_test_modules/nginx-eval-module --add-module=/usr/openresty/openresty_test_modules/replace-filter-nginx-module

And then tried to execute the test cases for 'stream-lua-nginx-module' like below -

[root stream-lua-nginx-module]# pwd
/usr/openresty/openresty_test_modules/stream-lua-nginx-module
[root stream-lua-nginx-module]# prove -r t/

NOTE: The 'stream-lua-nginx-module' source code used is latest one - Cloned from https://github.com/openresty/stream-lua-nginx-module

But I am getting below kind of errors (I have kept only uniq errors and removed the repeated lines) -

			
		[stream-lua-nginx-module]# prove -r t/
		t/002-content.t ..................... 1/96
		#   Failed test 'TEST 9: multiple eof - pattern "lua send eof" should match a line in error.log (req 0)'
		#   at /usr/local/share/perl5/Test/Nginx/Socket.pm line 1213.

		t/013-base64.t ...................... 31/78
		#   Failed test 'TEST 13: base64 encode with wrong 2nd parameter - pattern "(?^:runtime error: content_by_lua\(nginx\.conf:\d+\):\d+: bad no_padding: boolean expected, got number)" should match a line in error.log (req 0)'
		#   at /usr/local/share/perl5/Test/Nginx/Socket.pm line 1213.

		t/023-preread/exit.t ................ 1/8
		#   Failed test 'TEST 1: throw 500 - pattern "finalize stream request: 500" should match a line in error.log (req 0)'
		#   at /usr/local/share/perl5/Test/Nginx/Socket.pm line 1213.

		t/023-preread/req-socket.t .......... 1/94
		#   Failed test 'TEST 7: peeking preread buffer, buffer size is small - pattern "finalize stream session: 400" should match a line in error.log (req 0)'
		#   at /usr/local/share/perl5/Test/Nginx/Socket.pm line 1213.

		#   at /usr/local/share/perl5/Test/Nginx/Socket.pm line 1213.
		#   Failed test 'TEST 3: sleep 0.5 - multi-times - pattern "stream lua sleep timer expired" should match a line in error.log (req 0)'
		#   at /usr/local/share/perl5/Test/Nginx/Socket.pm line 1213.

		#   Failed test 'TEST 4: sleep 0.5 - interleaved by ngx.say() - ended by ngx.sleep - pattern "stream lua sleep timer expired" should match a line in error.log (req 0)'
		#   at /usr/local/share/perl5/Test/Nginx/Socket.pm line 1213.
		t/023-preread/sleep.t ............... 20/42
		#   Failed test 'TEST 4: sleep 0.5 - interleaved by ngx.say() - ended by ngx.sleep - pattern "lua ready to sleep" should match a line in error.log (req 1)'
		#   at /usr/local/share/perl5/Test/Nginx/Socket.pm line 1213.

		#   Failed test 'TEST 4: sleep 0.5 - interleaved by ngx.say() - ended by ngx.sleep - pattern "stream lua sleep timer expired" should match a line in error.log (req 1)'
		#   at /usr/local/share/perl5/Test/Nginx/Socket.pm line 1213.
		t/023-preread/sleep.t ............... 25/42
		#   Failed test 'TEST 5: sleep 0.5 - interleaved by ngx.say() - not ended by ngx.sleep - pattern "lua ready to sleep for" should match a line in error.log (req 0)'
		#   at /usr/local/share/perl5/Test/Nginx/Socket.pm line 1213.

		#   Failed test 'TEST 5: sleep 0.5 - interleaved by ngx.say() - not ended by ngx.sleep - pattern "stream lua sleep timer expired" should match a line in error.log (req 0)'
		#   at /usr/local/share/perl5/Test/Nginx/Socket.pm line 1213.

		#   Failed test 'TEST 5: sleep 0.5 - interleaved by ngx.say() - not ended by ngx.sleep - pattern "lua ready to sleep for" should match a line in error.log (req 1)'
		#   at /usr/local/share/perl5/Test/Nginx/Socket.pm line 1213.

		#   Failed test 'TEST 5: sleep 0.5 - interleaved by ngx.say() - not ended by ngx.sleep - pattern "stream lua sleep timer expired" should match a line in error.log (req 1)'
		#   at /usr/local/share/perl5/Test/Nginx/Socket.pm line 1213.
		t/023-preread/sleep.t ............... 35/42
		#   Failed test 'TEST 1: sleep 0.5 - pattern "lua ready to sleep for" should match a line in error.log (req 0)'
		#   at /usr/local/share/perl5/Test/Nginx/Socket.pm line 1213.

		#   Failed test 'TEST 1: sanity - grep_error_log_out (req 1)'
		#   at /usr/local/share/perl5/Test/Nginx/Socket.pm line 1149.
		# @@ -1,2 +0,0 @@
		# -lua tcp socket get keepalive peer: using connection
		# -lua tcp socket get keepalive peer: using connection

		#   Failed test 'TEST 5: connection timeout (tcp) - pattern "stream lua tcp socket connect timed out, when connecting to 127.0.0.2:12345" should match a line in error.log (req 1)'
		#   at /usr/local/share/perl5/Test/Nginx/Socket.pm line 1213.
		t/023-preread/tcp-socket.t .......... 25/48
		#   Failed test 'TEST 7: resolver error (host not found) - response_body_like - response is expected (failed to connect: blah-blah-not-found.agentzh.org could not be resolved (110: Operation timed out) connected: nil failed to send request: closed)'
		#   at /usr/local/share/perl5/Test/Nginx/Socket.pm line 1635.
		#                   'failed to connect: blah-blah-not-found.agentzh.org could not be resolved (110: Operation timed out)
		# connected: nil
		# failed to send request: closed
		# '
		#     doesn't match '(?^s:^failed to connect: blah-blah-not-found\.agentzh\.org could not be resolved(?: \(3: Host not found\))?
		# connected: nil
		# failed to send request: closed$
		# )'

		#   Failed test 'TEST 21: multiple parallel timers - pattern "stream lua ngx.timer expired" should match a line in error.log (req 0)'
		#   at /usr/local/share/perl5/Test/Nginx/Socket.pm line 1213.

		#   Failed test 'TEST 21: multiple parallel timers - pattern "stream lua finalize fake request" should match a line in error.log (req 0)'
		#   at /usr/local/share/perl5/Test/Nginx/Socket.pm line 1213.

		#   Failed test 'TEST 21: multiple parallel timers - pattern "stream lua decrementing the reference count for Lua VM: 3" should match a line in error.log (req 0)'
		#   at /usr/local/share/perl5/Test/Nginx/Socket.pm line 1213.

		#   Failed test 'TEST 21: multiple parallel timers - pattern "stream lua decrementing the reference count for Lua VM: 2" should match a line in error.log (req 0)'
		#   at /usr/local/share/perl5/Test/Nginx/Socket.pm line 1213.

		#   Failed test 'TEST 21: multiple parallel timers - pattern "stream lua decrementing the reference count for Lua VM: 1" should match a line in error.log (req 0)'
		#   at /usr/local/share/perl5/Test/Nginx/Socket.pm line 1213.

		#   Failed test 'TEST 21: multiple parallel timers - pattern "stream lua close the global Lua VM" should match a line in error.log (req 0)'
		#   at /usr/local/share/perl5/Test/Nginx/Socket.pm line 1213.

		#   Failed test 'TEST 21: multiple parallel timers - pattern "stream lua ngx.timer expired" should match a line in error.log (req 1)'
		#   at /usr/local/share/perl5/Test/Nginx/Socket.pm line 1213.

		#   Failed test 'TEST 21: multiple parallel timers - pattern "stream lua finalize fake request" should match a line in error.log (req 1)'
		#   at /usr/local/share/perl5/Test/Nginx/Socket.pm line 1213.

		#   Failed test 'TEST 21: multiple parallel timers - pattern "stream lua decrementing the reference count for Lua VM: 3" should match a line in error.log (req 1)'
		#   at /usr/local/share/perl5/Test/Nginx/Socket.pm line 1213.

		#   Failed test 'TEST 21: multiple parallel timers - pattern "stream lua decrementing the reference count for Lua VM: 2" should match a line in error.log (req 1)'
		#   at /usr/local/share/perl5/Test/Nginx/Socket.pm line 1213.

		#   Failed test 'TEST 21: multiple parallel timers - pattern "stream lua decrementing the reference count for Lua VM: 1" should match a line in error.log (req 1)'
		#   at /usr/local/share/perl5/Test/Nginx/Socket.pm line 1213.

		#   Failed test 'TEST 21: multiple parallel timers - pattern "stream lua close the global Lua VM" should match a line in error.log (req 1)'
		#   at /usr/local/share/perl5/Test/Nginx/Socket.pm line 1213.
		nginx: [alert] stream lua_code_cache is off; this will hurt performance in /usr/openresty/openresty_test_modules/stream-lua-nginx-module/t/servroot/conf/nginx.conf:23

		t/039-sub-o.t ....................... ok
		t/040-gsub-o.t ...................... ok
		t/042-crc32.t ....................... ok
		t/043-shdict.t ...................... 34/264 nginx: [crit] ngx_slab_alloc() failed: no memory
		nginx: [crit] ngx_slab_alloc() failed: no memory
		nginx: [crit] ngx_slab_alloc() failed: no memory
		nginx: [crit] ngx_slab_alloc() failed: no memory
		nginx: [crit] ngx_slab_alloc() failed: no memory

After the repeated "ngx_slab_alloc() failed: no memory" errors, the test case execution halts.

Please help suggest if I need to export any specific environment/setup any additional service or should try any compiler flag/somehow increase timeout value to make these test cases pass?

nginx version (compiled with libdrizzle 1.0 and radius, mariadb, postgresql services setup) -

	# nginx -V
	nginx version: openresty/1.17.1.1rc0
	built by gcc 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)
	built with OpenSSL 1.0.2k-fips  26 Jan 2017
	TLS SNI support enabled
	configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt='-O2 -DNGX_LUA_USE_ASSERT -DNGX_LUA_ABORT_AT_PANIC' --add-module=../ngx_devel_kit-0.3.1rc1 --add-module=../iconv-nginx-module-0.14 --add-module=../echo-nginx-module-0.61 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.32 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.08 --add-module=../drizzle-nginx-module-0.1.11 --add-module=../ngx_postgres-1.0 --add-module=../srcache-nginx-module-0.31 --add-module=../ngx_lua-0.10.15 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.15 --add-module=../rds-csv-nginx-module-0.09 --add-module=../ngx_stream_lua-0.0.7 --with-ld-opt=-Wl,-rpath,/usr/local/openresty/luajit/lib --with-http_image_filter_module --with-http_dav_module --with-http_auth_request_module --with-poll_module --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_ssl_module --with-http_addition_module --add-module=/usr/openresty/openresty_test_modules/nginx-eval-module --add-module=/usr/openresty/openresty_test_modules/replace-filter-nginx-module --with-stream --with-stream_ssl_preread_module

**Comment by SantoshMagdum** [comment]
Hi All,
Please share any pointers you have on way to resolve the above failures. Thanks in advance.

**Comment by zhuizhuhaomeng** [comment]
Close this issue since it is too old.
