### ISSUE TITLE
some way to skip ipv6 tests

### ISSUE THREAD

**Issue by chipitsine** [openresty/stream-lua-nginx-module#18]
have a look

https://travis-ci.org/chipitsine/stream-lua-nginx-module/jobs/126074290#L4872

same as lua-nginx-module, cannot bind ::1

**Comment by agentzh** [comment]
@chipitsine Yeah, they essentially share the same test suite :)

**Comment by chipitsine** [comment]
can we add my dirty hack (with ping6) for a while ?
we can replace it with better solution later

**Comment by agentzh** [comment]
@chipitsine As long as it has no other unwanted implications, then yes.

**Comment by chipitsine** [comment]
https://github.com/openresty/stream-lua-nginx-module/pull/19
