### ISSUE TITLE
api/ngx_stream_lua_api.h should export ngx_stream_lua_request_t

### ISSUE THREAD

**Issue by kyontan** [openresty/stream-lua-nginx-module#180]
Hi,

I think https://github.com/openresty/stream-lua-nginx-module/blob/master/src/api/ngx_stream_lua_api.h is not usable currently.
Since `ngx_stream_lua_request_t` defined in below, are not exported, including `ngx_stream_lua_api.h` solely makes compile failed.

https://github.com/openresty/stream-lua-nginx-module/blob/e3eb228c08e5bab30404d5d715bd9b5a545f68a8/src/ngx_stream_lua_request.h#L22-L35

Currently, I added `#include "../ngx_stream_lua_request.h"` to `ngx_stream_lua_api.h` for workaround, but only exporting `ngx_stream_lua_request_t` will be more suitable.

I want to submit pull request.  Is moving `ngx_stream_lua_request_t` to `ngx_stream_lua_api.h` and include `ngx_stream_lua_api.h` from `ngx_stream_lua_request.h` suitable?

**Comment by qiangcz** [comment]
i have met same problem when i build kong with openresty-build-tools.
```
../ngx_stream_lua-0.0.7/src/api/ngx_stream_lua_api.h:49:1: error: unknown type name 'ngx_stream_lua_request_t'; did you mean 'ngx_stream_lua_value_t'?
 ngx_stream_lua_request_t *ngx_stream_lua_get_request(lua_State *L);
```

anyone can resolve it?

**Comment by mkopeyka** [comment]
I have the same problem :(

**Comment by trypzz** [comment]
up. same problem too

**Comment by spacewander** [comment]
@doujiang24
Maybe we can delete `ngx_stream_lua_request_t *ngx_stream_lua_get_request(lua_State *L);` from the `api.h`? Since nobody could use it actually.

**Comment by doujiang24** [comment]
@spacewander Agreed.

**Comment by rainingmaster** [comment]
> @spacewander Agreed, let's do it.

According to my memory, this module will update when `ngx_meta_lua_module` release, and I remember the newest ngx_meta_lua_module has fix this problem?
