### ISSUE TITLE
command conflict, content_by_lua command is conflict with proxy_pass

### ISSUE THREAD

**Issue by scutkim** [openresty/stream-lua-nginx-module#196]
content_by_lua command process：
    { ngx_string("content_by_lua_file"),
      NGX_STREAM_SRV_CONF|NGX_CONF_TAKE1,
      ngx_stream_lua_content_by_lua,
      NGX_STREAM_SRV_CONF_OFFSET,
      0,
      (void *) ngx_stream_lua_content_handler_file },
	  
char *
ngx_stream_lua_content_by_lua(ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
{
...........
    /*  register location content handler */
    cxcf = ngx_stream_conf_get_module_srv_conf(cf, ngx_stream_core_module);
    if (cxcf == NULL) {
        return NGX_CONF_ERROR;
    }
    cxcf->handler = ngx_stream_lua_content_handler;
...........	
}

proxy_pass command process：
    { ngx_string("proxy_pass"),
      NGX_STREAM_SRV_CONF|NGX_CONF_TAKE1,
      ngx_stream_proxy_pass,
      NGX_STREAM_SRV_CONF_OFFSET,
      0,
      NULL },

static char *
ngx_stream_proxy_pass(ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
{
...........
    cscf = ngx_stream_conf_get_module_srv_conf(cf, ngx_stream_core_module);
    cscf->handler = ngx_stream_proxy_handler;
...........
}

those two command change the same cscf->handler. so it cause the conflict. when these two config command is in the stream server section at the same time. only one is effective.

Can you help me solve this problem?

**Comment by spacewander** [comment]
Both content_by_lua and proxy_pass are in the content phase and only one handler is allowed in content phase. It is expected behavior.
