### ISSUE TITLE
when include ngx_stream_lua_api.h at my module, compile error:

### ISSUE THREAD

**Issue by stone-wind** [openresty/stream-lua-nginx-module#198]
../ngx_stream_lua-0.0.8/src/api/ngx_stream_lua_api.h:56:1: error: unknown type name ‘ngx_stream_lua_request_t’; did you mean ‘ngx_stream_lua_value_t’?
 ngx_stream_lua_request_t *ngx_stream_lua_get_request(lua_State *L);
 ^~~~~~~~~~~~~~~~~~~~~~~~
 ngx_stream_lua_value_t

**Comment by spacewander** [comment]
Related issue #180
