### ISSUE TITLE
followup on my pull

### ISSUE THREAD

**Issue by itpp16** [openresty/stream-lua-nginx-module#2]
/src/ngx_stream_lua_util.c(1465) : error C2039: 'header_sent' : is not a member of 'ngx_stream_session_s'
        src/stream\ngx_stream.h(139) : see declaration of 'ngx_stream_session_s'
/src/ngx_stream_lua_util.c(1727) : error C2065: 'ngx_stream_lua_ssl_cert_ctx_t' : undeclared identifier
/src/ngx_stream_lua_util.c(1727) : error C2065: 'cctx' : undeclared identifier
/src/ngx_stream_lua_util.c(1727) : warning C4552: '*' : operator has no effect; expected operator with side-effect
/src/ngx_stream_lua_util.c(1750) : error C2065: 'cctx' : undeclared identifier
/src/ngx_stream_lua_util.c(1750) : warning C4013: 'ngx_stream_lua_ssl_get_ctx' undefined; assuming extern returning int
/src/ngx_stream_lua_util.c(1751) : error C2065: 'cctx' : undeclared identifier
/src/ngx_stream_lua_util.c(1751) : warning C4047: '!=' : 'int' differs in levels of indirection from 'void *'
/src/ngx_stream_lua_util.c(1752) : error C2065: 'cctx' : undeclared identifier
/src/ngx_stream_lua_util.c(1752) : error C2223: left of '->exit_code' must point to struct/union
/src/ngx_stream_lua_util.c(2900) : error C2065: 'ngx_stream_cleanup_t' : undeclared identifier

/src/ngx_stream_lua_socket_tcp.c(1238) : error C2039: 'ssl' : is not a member of 'ngx_stream_lua_srv_conf_t'
\src\ngx_stream_lua_common.h(159) : see declaration of 'ngx_stream_lua_srv_conf_t'
/src/ngx_stream_lua_socket_tcp.c(1238) : warning C4133: 'function' : incompatible types - from 'ngx_connection_t *' to 'ngx_ssl_t *'
/src/ngx_stream_lua_socket_tcp.c(1239) : warning C4047: 'function' : 'ngx_connection_t *' differs in levels of indirection from 'int'
/src/ngx_stream_lua_socket_tcp.c(1239) : warning C4024: 'ngx_ssl_create_connection' : different types for formal and actual parameter 2
/src/ngx_stream_lua_socket_tcp.c(1239) : error C2198: 'ngx_ssl_create_connection' : too few arguments for call

/src/ngx_stream_lua_sleep.c(73) : error C2039: 'uri' : is not a member of 'ngx_stream_session_s'
        src/stream\ngx_stream.h(139) : see declaration of 'ngx_stream_session_s'
/src/ngx_stream_lua_sleep.c(73) : error C2039: 'uri' : is not a member of 'ngx_stream_session_s'
        src/stream\ngx_stream.h(139) : see declaration of 'ngx_stream_session_s'

Specific warnings not logged yet.

**Comment by agentzh** [comment]
@itpp16 Thanks for the report. Will you try the latest git master again on your side?

**Comment by itpp16** [comment]
Still these:

/src/ngx_stream_lua_util.c(1720) : error C2065: 'ngx_stream_lua_ssl_cert_ctx_t' : undeclared identifier
/src/ngx_stream_lua_util.c(1720) : error C2065: 'cctx' : undeclared identifier
/src/ngx_stream_lua_util.c(1720) : warning C4552: '*' : operator has no effect; expected operator with side-effect
/src/ngx_stream_lua_util.c(1743) : error C2065: 'cctx' : undeclared identifier
/src/ngx_stream_lua_util.c(1743) : warning C4013: 'ngx_stream_lua_ssl_get_ctx' undefined; assuming extern returning int
/ngx_stream_lua_util.c(1744) : error C2065: 'cctx' : undeclared identifier
/src/ngx_stream_lua_util.c(1744) : warning C4047: '!=' : 'int' differs in levels of indirection from 'void *'
/src/ngx_stream_lua_util.c(1745) : error C2065: 'cctx' : undeclared identifier
/src/ngx_stream_lua_util.c(1745) : error C2223: left of '->exit_code' must point to struct/union

See also above with ngx_stream_lua_socket_tcp.c and ngx_stream_lua_sleep.c

**Comment by agentzh** [comment]
@itpp16 Committed a patch to git master. Please try again :)

**Comment by itpp16** [comment]
All fixed!
