### ISSUE TITLE
use stream macro

### ISSUE THREAD

**Issue by like-c** [openresty/stream-lua-nginx-module#205]
https://github.com/openresty/stream-lua-nginx-module/blob/a445407723e7e5075a6458c725961358d911fdbf/src/ngx_stream_lua_contentby.c#L148

**Comment by like-c** [comment]
please change NGX_LOG_DEBUG_HTTP to NGX_LOG_DEBUG_STREAM. thanks.

**Comment by spacewander** [comment]
@like-c 
Thanks for your report! I just submitted a fix for it.
