### ISSUE TITLE
sock:receive问题

### ISSUE THREAD

**Issue by ccx997t** [openresty/stream-lua-nginx-module#234]
1 看文档sock:receive('*a')需要the socket until the connection is closed，请求如果客户端不shutdownOutput，不进行关闭流，如何拿到tcp，sock:receive是否支持自定义正则表达式

2 比如有一个不定长的流，以8个5结尾作为结束，如何正确的读取每个请求

**Comment by zhuizhuhaomeng** [comment]
Please use  [receiveuntil](https://github.com/openresty/lua-nginx-module?tab=readme-ov-file#tcpsockreceiveuntil)
