### ISSUE TITLE
ngx_stream_lua_worker.c:124:8: error: ‘ngx_core_conf_t’ has no member named ‘privileged_agent_connections’

### ISSUE THREAD

**Issue by xahehe** [openresty/stream-lua-nginx-module#258]
stream-lua-nginx-module-master/src/ngx_stream_lua_worker.c:124:8: error: ‘ngx_core_conf_t’ has no member named ‘privileged_agent_connections’

  124 |     ccf->privileged_agent_connections = connections;

      |        ^~

gmake[2]: *** [objs/Makefile:3406: objs/addon/src/ngx_stream_lua_worker.o] Error 1

**Comment by xahehe** [comment]
**Also, has error like this:**
/usr/bin/ld: objs/addon/src/ngx_stream_lua_input_filters.o: in function `ngx_stream_lua_read_bytes':

/home/test/Workspace/Src/openresty-master/openresty-1.19.9.1rc1/../../stream-lua-nginx-module-master/src/ngx_stream_lua_input_filters.c:27: multiple definition of `ngx_stream_lua_read_bytes'; objs/addon/src/ngx_stream_lua_input_filters.o:/home/test/Workspace/Src/openresty-master/openresty-1.19.9.1rc1/../../stream-lua-nginx-module-master/src/ngx_stream_lua_input_filters.c:27: first defined here

/usr/bin/ld: objs/addon/src/ngx_stream_lua_input_filters.o: in function `ngx_stream_lua_read_all':

/home/test/Workspace/Src/openresty-master/openresty-1.19.9.1rc1/../../stream-lua-nginx-module-master/src/ngx_stream_lua_input_filters.c:54: multiple definition of `ngx_stream_lua_read_all'; objs/addon/src/ngx_stream_lua_input_filters.o:/home/test/Workspace/Src/openresty-master/openresty-1.19.9.1rc1/../../stream-lua-nginx-module-master/src/ngx_stream_lua_input_filters.c:54: first defined here

/usr/bin/ld: objs/addon/src/ngx_stream_lua_input_filters.o: in function `ngx_stream_lua_read_any':

/home/test/Workspace/Src/openresty-master/openresty-1.19.9.1rc1/../../stream-lua-nginx-module-master/src/ngx_stream_lua_input_filters.c:69: multiple definition of `ngx_stream_lua_read_any'; objs/addon/src/ngx_stream_lua_input_filters.o:/home/test/Workspace/Src/openresty-master/openresty-1.19.9.1rc1/../../stream-lua-nginx-module-master/src/ngx_stream_lua_input_filters.c:69: first defined here

/usr/bin/ld: objs/addon/src/ngx_stream_lua_input_filters.o: in function `ngx_stream_lua_read_line':

/home/test/Workspace/Src/openresty-master/openresty-1.19.9.1rc1/../../stream-lua-nginx-module-master/src/ngx_stream_lua_input_filters.c:88: multiple definition of `ngx_stream_lua_read_line'; objs/addon/src/ngx_stream_lua_input_filters.o:/home/test/Workspace/Src/openresty-master/openresty-1.19.9.1rc1/../../stream-lua-nginx-module-master/src/ngx_stream_lua_input_filters.c:88: first defined here

collect2: error: ld returned 1 exit status

gmake[2]: *** [objs/Makefile:525: objs/nginx] Error 1

gmake[2]: Leaving directory '/home/test/Workspace/Src/openresty-master/openresty-1.19.9.1rc1/build/nginx-1.19.9'

gmake[1]: *** [Makefile:10: build] Error 2

gmake[1]: Leaving directory '/home/test/Workspace/Src/openresty-master/openresty-1.19.9.1rc1/build/nginx-1.19.9'

gmake: *** [Makefile:9: all] Error 2

**Comment by zhuizhuhaomeng** [comment]
thank you for your reporting

**Comment by zhuizhuhaomeng** [comment]
this issue has been resolved，please update to the latest version.
better to use https://github.com/openresty/openresty/blob/master/util/mirror-tarballs to get the latest tarball
will apply the patch automatically

**Comment by lazy-wangxl** [comment]
@zhuizhuhaomeng Thanks very much!
