### ISSUE TITLE
Lua blocks cannot coexist with proxy_pass, only proxy_pass is executed when proxy_pass is present

### ISSUE THREAD

**Issue by hhwode** [openresty/stream-lua-nginx-module#260]
when I write lua at stream, I found lua blocks cannot coexist with proxy_pass, only proxy_pass is executed when proxy_pass is present.
Env:
openresty-1.19.3.1
stream-lua-nginx-module-0.0.8
Code:
`stream {
     lua_add_variable $url;
     server {
        listen 8000;
        set $url "ddddddddddddd";
        content_by_lua_block {
            ngx.say("========== Start to ");
            ngx.say(ngx.var.url);
            ngx.var.url="127.0.0.1:22";
            ngx.say(ngx.var.url);
        }
        proxy_pass $url;
    }
}`

**Comment by anand-010** [comment]
Do you found any solution I 've similar problem #295.
Please resolve if you can.
