### ISSUE TITLE
upstream or downstream

### ISSUE THREAD

**Issue by alonbg** [openresty/stream-lua-nginx-module#29]
server {
      listen 9003;
      content_by_lua_block {
        local tcpsock = ngx.req.socket(true)
        while true do
            local data, err = tcpsock:receive(5)
            if not data then
             ngx.say("failed to read data", err)
            return
            end
            ngx.say("successfully read: ", data)
        end
  }
}

Above has no upstream defined. However, data is received from the client.
Is this expected ? Is upstream simply short-circuited to downstream in this case ? 

My intention is to intercept and read upstream before proxy_pass directive takes effect.
Would that require the future TODO `access_by_lua_block` feature ?

**Comment by agentzh** [comment]
@alonbg There is no such thing as "request body" defined in the stream context since there is no pre-determined definition of a "request body" in the generic TCP world. So you cannot directly apply the concept of buffered request bodies of the http subsystem to the stream subsystem. For your use case, you should use cosockets to do the proxying part in Lua as well.

**Comment by alonbg** [comment]
That's true.  I wasn't clear. Sorry for that.
I've rewritten the issue description.
Thanks

**Comment by agentzh** [comment]
@alonbg You can only have either content_by_lua* or proxy_pass in a single location but never both. They are exclusive. I think I've talk you that before.

**Comment by alonbg** [comment]
I probably misunderstood this.
However,  access_by_lua,  once developed,  will be at to coexist with proxy_pass?

**Comment by agentzh** [comment]
@alonbg Yes, because they run in different nginx request processing phases (access vs content).

**Comment by alonbg** [comment]
And if I need to intercept both downstream and upstream my only option would be upstreaming with Lua sockets? 
Can this be done from access_by_lua*?

**Comment by agentzh** [comment]
@alonbg By "upstream cosocket API", I mean this Lua API:

https://github.com/openresty/lua-nginx-module/#ngxsockettcp

I'm not talking about ngx_stream_proxy_module here.

**Comment by alonbg** [comment]
@agentzh Thank you for your patience :). This is what I thought. 
Now the above seems less of an issue and more of a discussion.
Sorry for that. I'll take additional questions to the forum :) 
access_by_lua* is already on the TODO, thus I'm closing this ticket.

Thanks
