### ISSUE TITLE
ld: symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by jlynet** [openresty/stream-lua-nginx-module#292]
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [objs/nginx] Error 1
make: *** [build] Error 2

**Comment by zhuizhuhaomeng** [comment]
some key messages are lost.
need the full build log

**Comment by zhuizhuhaomeng** [comment]
The issue was closed as there was no further information.
