### ISSUE TITLE
[bug] connection won't be closed when using ngx.thread.spawn

### ISSUE THREAD

**Issue by mike07026** [openresty/stream-lua-nginx-module#31]
Example: test.lua

```
local function say_hello()
    return ngx.say("hello")
end

for i = 1, 3 do

    ngx.sleep(1.0)
    local co = ngx.thread.spawn(say_hello)
    ngx.thread.wait(co)

end

-- the clinet connection will not be close
-- it's a bug, but we can workaround with ngx.sleep
--ngx.sleep(0.001)
```
After printing three "hello", the client's connection won't be closed after the "world" exit.
It's a bug, but we can workaround with ngx.sleep.

I run this code under stream-lua-nginx-module and listen port 1234, here is the result
```
nc 127.0.0.1 1234
hello
hello
hello
-- wait here forever, the connection won't be closed.
```

if  uncomment code "ngx.sleep(0.001)", the connection will be closed correctly.
```
nc 127.0.0.1 1234
hello
hello
hello
-- connection closed.
```

**Comment by agentzh** [comment]
> After printing three "hello", the client's connection won't be closed after the "world" exit.

What do you mean by "world"? I don't see anything called `world` in your code snippet. Am I missing anything here?

**Comment by agentzh** [comment]
@mike07026 I just committed a fix for the hanging problem in the thread-hanging branch of this git repository as commit 75e0b16. Please try it out on your side. Thanks for your report!

**Comment by agentzh** [comment]
@mike07026 Just merged into master. Feel free to re-open this if you still have the problem.

**Comment by mike07026** [comment]
@agentzh It works, thank you.
