### ISSUE TITLE
[Improvement] Add License File to Project

### ISSUE THREAD

**Issue by conradkirschner** [openresty/stream-lua-nginx-module#315]
In the Readme it's written: 
`If you are using this module, then you are essentially using OpenResty.`

Does it mean I am allowed to use it or is this private code?

**Comment by zhuizhuhaomeng** [comment]
The license is already in readme: https://github.com/openresty/stream-lua-nginx-module#copyright-and-license

**Comment by conradkirschner** [comment]
Is it possible to create a license file? This makes it easier to see, also github will display it as icon
