### ISSUE TITLE
Will nginx1.21.5 still be supported？

### ISSUE THREAD

**Issue by swzaaaaaaa** [openresty/stream-lua-nginx-module#317]

**Comment by zhuizhuhaomeng** [comment]
No. 
The next release will be openresty-1.25.x which contains the nginx-1.25.x.

**Comment by zhuizhuhaomeng** [comment]
For the stream-lua-nginx-module, it is compatible with 1.21.5.

**Comment by swzaaaaaaa** [comment]
Have you tested it in 1.21.5?I see a maximum fit of 1.19.1.

**Comment by zhuizhuhaomeng** [comment]
We did not test on 1.21.5. 
The latest release version of openresty is 1.21.4.

**Comment by zhuizhuhaomeng** [comment]
We did not test on 1.21.5. 
The latest release version of Openresty is 1.21.4.

**Comment by swzaaaaaaa** [comment]
What are the versions of luajit and stream_lua-nginx in the 1.25.1 test environment, and is lua-resty-core required?

**Comment by zhuizhuhaomeng** [comment]
lua-resty-core is always required.
