### ISSUE TITLE
About the timeout period

### ISSUE THREAD

**Issue by coderwxl** [openresty/stream-lua-nginx-module#332]
Is there a way to set the timeout between the successful connection and the first time we receive the client request data?

**Comment by tzssangglass** [comment]
> Is there a way to set the timeout between the successful connection and the first time we receive the client request data?

`lua_socket_read_timeout` ?

**Comment by zhuizhuhaomeng** [comment]
> Is there a way to set the timeout between the successful connection and the first time we receive the client request data?
