### ISSUE TITLE
how to close a ngx.req.socket(true)

### ISSUE THREAD

**Issue by tangwz** [openresty/stream-lua-nginx-module#35]
I use this module to develop a tcp server, I need close the connection but the tcp created by ngx.req.socket cannot be closed. How can I do?

I user websocket before.Forgive me do not use websocket here.

**Comment by agentzh** [comment]
@tangwz It's closed automatically when your current Lua handler (like `content_by_lua*`) finishes running. It does not make much sense to expose a `close` method to allow the user to close it explicitly IMHO.

**Comment by tangwz** [comment]
Thanks. Maybe more research is needed to understand.

**Comment by poembro** [comment]
If client power off or computer broken network, I need  to actively  close the "ngx.req.socket(true)" connection. How can I do?

**Comment by agentzh** [comment]
@poembro Please do not hijack unrelated issues, especially those already closed ones like this. Regarding your question, you should look at TCP keep-alive configurations, for example.
