### ISSUE TITLE
config or configure ?

### ISSUE THREAD

**Issue by aifeiasdf** [openresty/stream-lua-nginx-module#4]

**Comment by agentzh** [comment]
@aifeiasdf Every NGINX C module provides a `config` file for NGINX or OpenResty's build system (`./configure`) to pick up. You should use the `--add-module=PATH` option in NGINX or OpenResty's `./configure` script to add this module into your NGINX or OpenResty build.

**Comment by agentzh** [comment]
@aifeiasdf See https://github.com/openresty/stream-lua-nginx-module#installation for more details on installation.
