### ISSUE TITLE
Can I share some vars to the http block

### ISSUE THREAD

**Issue by jeppojeps** [openresty/stream-lua-nginx-module#45]
Hello I am working with the ngx_stream_ssl_preread_module and I would like to share some vars between stream and http blocks. In the http block I am using LUA, I was thinking that maybe with stream-lua I'd be able to share some data, but it looks like I can't do that. because IMHO 2 different LUA interpreters will be launched for the 2 modules. If you have any hints they'd be welcome.

Thanks,
Jeppo

**Comment by agentzh** [comment]
@jeppojeps Right, they are separate subsystems in NGINX and also separate Lua VM instances. We may be able to share lua_shared_dict across the http and stream subsystems in the near future though.

**Comment by jeppojeps** [comment]
Hello, I am playing with the shared vars, I have created a new directive and modified the handler function copying it from the shared dict of stream, my change is in the call of ngx_shared_memory_add, instead of passing the stream_lua_module I am giving the http_core_module, it looks like the var is created but I can't access it from http, is there any other modification that I need to handle to make it work?

**Comment by agentzh** [comment]
@jeppojeps Read the discussion here:

https://github.com/openresty/stream-lua-nginx-module/pull/36

**Comment by dndx** [comment]
Hello,

In the long term we will probably make shdict shareable between subsystems. But will unlikely share Lua VM or NGINX variables across subsystems for sanity reasons.
