### ISSUE TITLE
core dump introduced in the last commit

### ISSUE THREAD

**Issue by chipitsine** [openresty/stream-lua-nginx-module#46]
hello,

I added "gdb backtrace" to travis-ci,

have a look

https://travis-ci.org/chipitsine/stream-lua-nginx-module/jobs/174301008#L1022

**Comment by agentzh** [comment]
@chipitsine It was actually a bug in those tests. Those tests are testing C APIs of ngx_http_lua_module instead of the current ngx_stream_lua_module.

**Comment by agentzh** [comment]
Already committed a fix to master.

**Comment by agentzh** [comment]
@chipitsine Thanks for the report!

BTW, the backtrace of the crash site is usually not very helpful since it is often not the culprit. Using valgrind is much more reliable.
