### ISSUE TITLE
Can I compile the module as dynamic

### ISSUE THREAD

**Issue by jeppojeps** [openresty/stream-lua-nginx-module#48]
Hello, I have tried to compile the module with the --add-dynamic-module flag in the configure script but I don't find any .so file, so my understanding is that I need to modify the config file, or maybe it is not possible at all to have it as dynamic.

Thanks

**Comment by agentzh** [comment]
@jeppojeps It's not yet supported. Patches welcome (you can take a look at ngx_http_lua_module's `config` file for reference).

**Comment by thibaultcha** [comment]
This is now supported since the 1.17.8.1rc1 release which will soon become mainstream.
