### ISSUE TITLE
Can't compile additional modules

### ISSUE THREAD

**Issue by ZigzagAK** [openresty/stream-lua-nginx-module#52]
Can't compile my module https://github.com/ZigzagAK/lua-stream-upstream-nginx-module (support lua api for stream).

Output:
1) trouble №1
cc1: warnings being treated as errors
stream-lua-nginx-module/src/ngx_stream_lua_util.c: В функции ‘ngx_stream_lua_free_session’:
stream-lua-nginx-module/src/ngx_stream_lua_util.c:3206: ошибка: неявная декларация функции ‘ngx_stream_close_connection’

2) trouble №2 on compilation my module because there are no implementation has been found in stream-lua-nginx-module.
objs/addon/src/ngx_stream_lua_upstream_module.o: In function `ngx_stream_lua_upstream_init':
/home/aleksey/nginx/nginx-1.11.5-src/lua-stream-upstream-nginx-module/src/ngx_stream_lua_upstream_module.c:63: undefined reference to `ngx_stream_lua_add_package_preload'
objs/addon/src/ngx_stream_lua_upstream_module.o: In function `ngx_stream_lua_upstream_get_upstream_main_conf':
/home/aleksey/nginx/nginx-1.11.5-src/lua-stream-upstream-nginx-module/src/ngx_stream_lua_upstream_module.c:487: undefined reference to `ngx_stream_lua_get_session'
objs/addon/src/ngx_stream_lua_upstream_module.o: In function `ngx_stream_lua_upstream_current_upstream_name':
/home/aleksey/nginx/nginx-1.11.5-src/lua-stream-upstream-nginx-module/src/ngx_stream_lua_upstream_module.c:557: undefined reference to `ngx_stream_lua_get_session'

Reason:
2 patches:
    1. nginx.patch
[nginx.patch.gz](https://github.com/openresty/stream-lua-nginx-module/files/602069/nginx.patch.gz)

    2. stream-lua-nginx-module.patch
[stream-lua-nginx-module.patch.gz](https://github.com/openresty/stream-lua-nginx-module/files/602070/stream-lua-nginx-module.patch.gz)

**Comment by agentzh** [comment]
@ZigzagAK Are you reporting problems in your own nginx module here? I'm afraid it's already off topic. This is ngx_stream_lua_module's repository.

**Comment by ZigzagAK** [comment]
> Are you reporting problems in your own nginx module here?
No.
The problem is in stream-lua-nginx-module.
I can't find implementation some functions in stream-lua-nginx-module:
ngx_stream_lua_add_package_preload - no implementation (declaration only in ngx_stream_lua_api.h)
ngx_stream_lua_get_session - implementation is in ngx_stream_lua_util.h (static ngx_inline ngx_stream_session_t * ngx_stream_lua_get_session(lua_State *L))

In this patch:
1. i remove ngx_stream_lua_get_session from  ngx_stream_lua_util.h and place it into ngx_stream_lua_api.c (new file).
2. add ngx_stream_lua_add_package_preload implementation into ngx_stream_lua_api.c.

After these modifications my module was compiled successfully.

Thanks.

**Comment by ZigzagAK** [comment]
Implementation of the simular http functions is located in ngx_http_lua_api.c ( lua-nginx-module )

**Comment by agentzh** [comment]
@ZigzagAK Right. Those C functions are not implemented yet. It's still a TODO.

**Comment by agentzh** [comment]
@ZigzagAK You're welcome to create pull requests to port them over from the ngx_http_lua module.
