### ISSUE TITLE
error: assignment from incompatible pointer type [-Werror]

### ISSUE THREAD

**Issue by alexmango** [openresty/stream-lua-nginx-module#54]
nginx1.9.15  make 编译错误，具体输出如下：
../nginx_module/stream-lua-nginx-module-0.0.1/src/ngx_stream_lua_socket_tcp.c: In function ‘ngx_stream_lua_socket_resolve_handler’:
../nginx_module/stream-lua-nginx-module-0.0.1/src/ngx_stream_lua_socket_tcp.c:819:15: error: assignment from incompatible pointer type [-Werror]
cc1: all warnings being treated as errors
make[1]: *** [objs/addon/src/ngx_stream_lua_socket_tcp.o] Error 1
make[1]: Leaving directory `/data/build/nginx-1.9.15'
make: *** [build] Error 2

操作系统：Ubuntu 12.04 LTS  64bit
nginx 版本： nginx 1.9.15
stream-lua-nginx-module 版本：stream-lua-nginx-module-0.0.1
gcc 版本： 4.6.3

configure 脚本：
./configure --prefix=/opt/nginx-1.9.15 --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_stub_status_module --with-file-aio --with-stream --with-stream_ssl_module  --add-module=../nginx_module/stream-lua-nginx-module-0.0.1  --with-cc-opt='-O2 -g' --with-ld-opt="-Wl,-rpath,/opt/luajit-2.0.4/lib"

@agentzh

**Comment by alexmango** [comment]
对比了一下 nginx 1.9.7 和 1.9.15 的源码，发现是 core/ngx_resolver.h 中的 struct ngx_resolver_ctx_s 定义发生了改变，它的 addrs 变成了 ngx_resolver_addr_t 指针而不是 ngx_addr_t  。但是对源码不太熟，不清楚怎么改。

**Comment by agentzh** [comment]
@alexmango Please, no Chinese here. This place is considered English only. If you really want to use Chinese, please join and post to the openresty (chinese) mailing list instead. Please see http://openresty.org/en/community.html Thanks for your cooperation.

**Comment by alexmango** [comment]
Thank you very much,
I have found the solution by download latest master of this repository.

**Comment by SuzyXiuzhi** [comment]
I“I have found the solution by download latest master of this repository.” Thanks, it works. But I got another problem:

/download/stream-lua-nginx-module/src/ngx_stream_lua_util.c: In function ‘ngx_stream_lua_free_session’:
/download/stream-lua-nginx-module/src/ngx_stream_lua_util.c:3206:9: error: implicit declaration of function ‘ngx_stream_close_connection’ [-Werror=implicit-function-declaration]

My nginx version:1.11.6
