### ISSUE TITLE
Is there a way to support tcp level domain (server_name) port streaming? 

### ISSUE THREAD

**Issue by Adel-Magebinary** [openresty/stream-lua-nginx-module#64]
Hello Team,

Is there a possibility of implementing domain support into nginx stream tcp layer? I understand tcp/ip protocol doesn't care about domain names ....

**Comment by agentzh** [comment]
@Adel-Magebinary Right. You have to do that yourself in your own TCP wire protocol (just like other overlay protocols such as http).
