### ISSUE TITLE
 fatal error: ngx_stream.h: No such file or directory

### ISSUE THREAD

**Issue by MrNsfocus** [openresty/stream-lua-nginx-module#69]
cd openresty-1.11.2.1
./configure --prefix=/usr/local/openresty \
            --with-luajit \
            --without-http_redis2_module \
            --add-module=../stream-lua-nginx-module-master \
            --with-threads \
            --with-pcre \
            --with-pcre-jit

**Comment by RocFang** [comment]
--with-stream

**Comment by dndx** [comment]
@RocFang yep.
