### ISSUE TITLE
Able to rewrite proxy_pass server?

### ISSUE THREAD

**Issue by ldelossa** [openresty/stream-lua-nginx-module#70]
Hello,

I'm attempting to dynamically route tcp traffic with Lua. Is this possible with this module? I want to have Lua grab a value from redis and set this as the backend per request.

**Comment by chinajinhongyu** [comment]
I also want to do that , but  failed.
Maybe the current version does not support this feature yet.

**Comment by agentzh** [comment]
It will soon be possible with `balancer_by_lua*` and `preread_by_lua*` handlers in this module.

**Comment by chinajinhongyu** [comment]
I think we can do it by **ngx.req.socket and ngx.socket.tcp** in stream-lua-nginx-module.
and I found an alternative, it worked perfectly, it is **ngx_mruby**(https://github.com/matsumotory/ngx_mruby/).

**Comment by narci2010** [comment]
good solution！thanks！

**Comment by dndx** [comment]
Hello!

This is possible through one of the two ways:
1. Use the `balancer_by_lua_*` support inside stream_lua or
2. Use the [lua_add_variable](https://github.com/openresty/stream-lua-nginx-module#lua_add_variable) directive to create a variable and change it using Lua, and use it with `proxy_pass $variable;`

Hope this helps.
