### ISSUE TITLE
Is the module supporting to get mysql sending data from "content_by_lua_block" ?

### ISSUE THREAD

**Issue by zcfrank1st** [openresty/stream-lua-nginx-module#71]
I have tried to use the module to get sql statements, but I got nil. Is it possible to use this module to get the mysql tcp data? Thanks~

**Comment by membphis** [comment]
This module should support `lua-resty-mysql`, and if you have this question, please provide a mini case about your question.

**Comment by agentzh** [comment]
Consider it resolved.
