### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by wbcb** [openresty/stream-lua-nginx-module#73]
I want to make a redis proxy. when I start my demo service with ip:port, the demo service works, 

shell> redis-cli -h 10.171.233.97 -p 1234
redis 10.171.233.97:1234> foo
OK
redis 10.171.233.97:1234> bar
OK

but when i start it with unix domain socket, it only work at first time request, it will exit at second time request.

shell> redis-cli -s /tmp/redis.sock
redis /tmp/redis.sock> foo
OK
redis /tmp/redis.sock> bar
[exit]

I test my demo service through redis-cli, I strace it, when it exit, I find error msg (Broken pipe)

nginx.conf & test.lua: https://gist.github.com/wbcb/a4be7693d9f1cb395c9ad5de8ad1edb7

**Comment by agentzh** [comment]
@wbcb There is no keepalive support in nginx's stream subsystem by default. You should put your server handler inside a Lua loop (preferably *not* an infinite loop).
