### ISSUE TITLE
why not support set_by_lua、set_by_lua_block?

### ISSUE THREAD

**Issue by narci2010** [openresty/stream-lua-nginx-module#74]
eager need...

**Comment by narci2010** [comment]
set_by_lua
set_by_lua_block
set_by_lua_file

**Comment by agentzh** [comment]
@narci2010 Because you'll be able to do nginx variable assignment in the upcoming `preread_by_lua*` handler feature which also supports those Lua APIs with yielding. The `set_by_lua*` thing in the http module is a hack at best.
