### ISSUE TITLE
How can I get the socket response??

### ISSUE THREAD

**Issue by psyun** [openresty/stream-lua-nginx-module#75]
We proxy tcp message by nginx+lua .the architecture like below... but i don't know how to get the proxy response message...

![image](https://user-images.githubusercontent.com/15973930/30492424-fa690c26-9a72-11e7-91e7-455cb93f3a9a.png)

**Comment by agentzh** [comment]
@psyun Just use the TCP cosocket API on the Lua land instead of using NGINX's own stream proxy module.
