### ISSUE TITLE
ngx.req.udp_socket is not work, why?

### ISSUE THREAD

**Issue by fx408** [openresty/stream-lua-nginx-module#76]
**error:** `lua entry thread aborted: runtime error: content_by_lua(nginx.conf:25):4: attempt to call field 'udp_socket' (a nil value)`

nginx.conf :

```
stream{
        server{
                listen 81 udp;
                content_by_lua_block {
                        local sock = ngx.req.udp_socket()
                        sock:send("Ok\n\n")
                }
        }
}
```

**Comment by agentzh** [comment]
@fx408 I'm afraid it's in the bloody-dns-server branch only. It's not in the master (yet).

**Comment by fx408** [comment]
@agentzh ， thanks

1. src/ngx_stream_lua_util.c：
replacing `ngx_stream_close_connection(s->connection);` with `ngx_stream_finalize_session(s, NGX_STREAM_INTERNAL_SERVER_ERROR);`

2. install libmaxminddb

And then succeeded。
