### ISSUE TITLE
Is HTTP or Stream

### ISSUE THREAD

**Issue by splitice** [openresty/stream-lua-nginx-module#8]
When in phases with the same name it is often necessary to know if the phase is executing in the http module system or the stream modules system.

Perhaps a variable or a method like ```get_phase``` (```get_system```?)?

**Comment by agentzh** [comment]
@splitice Yeah, I was thinking about adding an `ngx.config.subsystem` field that takes the value "http" or "stream". Feel free to create a PR for it :)

**Comment by splitice** [comment]
That'd work, I'll take a look and see what I can do when I get a chance.

**Comment by agentzh** [comment]
@splitice Thanks!

**Comment by agentzh** [comment]
This is already implemented in both ngx_stream_lua and ngx_http_lua. I'm closing this.
