### ISSUE TITLE
FFI ngx_http_lua_set_req equivilent

### ISSUE THREAD

**Issue by splitice** [openresty/stream-lua-nginx-module#9]
As far as I can see there is no equivalent to ```getfenv(0).__ngx_req``` for the stream session as far as I can see implemented in the lua stream module.

I dont think I can implement this one myself, however it is a requirement for the FFI side of balancer_by_lua_* (#7)

**Comment by agentzh** [comment]
@splitice We use `__ngx_sess` in this context instead.

**Comment by splitice** [comment]
Thanks I couldn't find that.
