### ISSUE TITLE
 'NGX_STREAM_INTERNAL_SERVER_ERROR' undeclared (first use in this function)

### ISSUE THREAD

**Issue by chrisforbt** [openresty/stream-lua-nginx-module#93]
/tmp/stream-lua-nginx-module/src/ngx_stream_lua_request.c: In function 'ngx_stream_lua_block_reading':
/tmp/stream-lua-nginx-module/src/ngx_stream_lua_request.c:187:53: error: 'NGX_STREAM_INTERNAL_SERVER_ERROR' undeclared (first use in this function)
             ngx_stream_lua_finalize_real_request(r, NGX_STREAM_INTERNAL_SERVER_ERROR);
                                                     ^
/tmp/stream-lua-nginx-module/src/ngx_stream_lua_request.c:187:53: note: each undeclared identifier is reported only once for each function it appears in
/tmp/stream-lua-nginx-module/src/ngx_stream_lua_request.c: In function 'ngx_stream_lua_finalize_real_request':
/tmp/stream-lua-nginx-module/src/ngx_stream_lua_request.c:207:14: error: 'NGX_STREAM_INTERNAL_SERVER_ERROR' undeclared (first use in this function)
         rc = NGX_STREAM_INTERNAL_SERVER_ERROR;
              ^
/tmp/stream-lua-nginx-module/src/ngx_stream_lua_request.c:219:14: error: 'NGX_STREAM_OK' undeclared (first use in this function)
         rc = NGX_STREAM_OK;

Is there something I need to install before? Here is my configure:
./configure --add-module=/tmp/stream-lua-nginx-module --with-luajit --with-stream --prefix=/usr/local/openresty

**Comment by agentzh** [comment]
@chrisforbt Seems like your nginx core is just too old.

**Comment by dndx** [comment]
@agentzh is right. You need to update your NGINX core.
