### ISSUE TITLE
Dynamic SSL?

### ISSUE THREAD

**Issue by moseleymark** [openresty/stream-lua-nginx-module#96]
Was just curious if adding the various ssl_certificate_by_lua_* directives to the openresty/streaming was still on the roadmap? Thanks!

**Comment by agentzh** [comment]
Yes, it's on the plan. Pull requests welcome though :)

**Comment by adugeek** [comment]
I had done this work . but have no time to make an PR .

**Comment by thibaultcha** [comment]
Implemented in 13210db2262c59ee2923f26b2f96c8de6636364c, which is merged and part of the latest rc of this module (and next formal release). Considering this resolved.

**Comment by moseleymark** [comment]
I've briefly tested the stream+ssl_certificate_by_lua_* over the weekend. With brief testing, it worked just fine.

This is truly awesome stuff. Can't thank you all enough.

**Comment by musab1** [comment]
@moseleymark 

Do you have a working example? i am trying to use stream with ssl_certificiate_by_lua - but absotlutely not lucky in here. 

Actually i am trying to implement https://github.com/GUI/lua-resty-auto-ssl
in the stream section -but always getting

2019/09/29 22:49:00 [error] 13937#0: *11 lua entry thread aborted: runtime error: ssl_certificate_by_lua:2: attempt to index global 'auto_ssl' (a nil value)
stack traceback:
coroutine 0:
        ssl_certificate_by_lua: in main chunk, context: ssl_certificate_by_lua*, client: 80.253.94.7, server: 0.0.0.0:993
2019/09/29 22:49:00 [crit] 13937#0: *10 SSL_do_handshake() failed (SSL: error:1417A179:SSL routines:tls_post_process_client_hello:cert cb error) while SSL handshaking, client: 80.253.94.7, server: 0.0.0.0:993
(END)


or dont know if this is more to ask the resty-auto-ssl devs.

but maybe with some working example i could get it.

**Comment by xiangcai1215** [comment]
> @moseleymark
> 
> Do you have a working example? i am trying to use stream with ssl_certificiate_by_lua - but absotlutely not lucky in here.
> 
> Actually i am trying to implement https://github.com/GUI/lua-resty-auto-ssl
> in the stream section -but always getting
> 
> 2019/09/29 22:49:00 [error] 13937#0: _11 lua entry thread aborted: runtime error: ssl_certificate_by_lua:2: attempt to index global 'auto_ssl' (a nil value) stack traceback: coroutine 0: ssl_certificate_by_lua: in main chunk, context: ssl_certificate_by_lua_, client: 80.253.94.7, server: 0.0.0.0:993
> 2019/09/29 22:49:00 [crit] 13937#0: *10 SSL_do_handshake() failed (SSL: error:1417A179:SSL routines:tls_post_process_client_hello:cert cb error) while SSL handshaking, client: 80.253.94.7, server: 0.0.0.0:993
> (END)
> 
> or dont know if this is more to ask the resty-auto-ssl devs.
> 
> but maybe with some working example i could get it.

did you  handle this problem?

**Comment by moseleymark** [comment]
> @moseleymark
> 
> Do you have a working example? i am trying to use stream with ssl_certificiate_by_lua - but absotlutely not lucky in here.
> 
> Actually i am trying to implement https://github.com/GUI/lua-resty-auto-ssl
> in the stream section -but always getting
> 
> 2019/09/29 22:49:00 [error] 13937#0: _11 lua entry thread aborted: runtime error: ssl_certificate_by_lua:2: attempt to index global 'auto_ssl' (a nil value) stack traceback: coroutine 0: ssl_certificate_by_lua: in main chunk, context: ssl_certificate_by_lua_, client: 80.253.94.7, server: 0.0.0.0:993
> 2019/09/29 22:49:00 [crit] 13937#0: *10 SSL_do_handshake() failed (SSL: error:1417A179:SSL routines:tls_post_process_client_hello:cert cb error) while SSL handshaking, client: 80.253.94.7, server: 0.0.0.0:993
> (END)
> 
> or dont know if this is more to ask the resty-auto-ssl devs.
> 
> but maybe with some working example i could get it.

Sorry, I wasn't using that module. I was working with the nginx/lua API directly. We do all of our LetsEncrypt certs out-of-band. Judging by that error, it sounds like you need a 'require()' for that module, maybe in the init_by_lua section?
